#Runs health check everyday at 00:00
#Uncomment to enable

#name: Periodic healthcheck

#on:
#  schedule:
#    - cron: '0 0 * * *'

#jobs:
#  health_check:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: healthcheck
#        uses: jtalk/url-health-check-action@v2
#        with:
#          url: https://pokedex-fullstack2022.herokuapp.com/health